app_version: 0.1.2
capabilities: []
categories:
- productivity
date_added: '2026-01-27'
description: A shared wishlist application for collaborative gift planning. Create wishlists, add items, and share with friends and family.
home: https://github.com/XmlmXmlmX/wunero
host_mounts: []
icon: https://raw.githubusercontent.com/XmlmXmlmX/wunero/main/public/favicon.ico
keywords:
- wishlist
- gifts
- sharing
- collaboration
- planning
lib_version: 2.1.60
lib_version_hash: ""
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.ixsystems.com/
name: wunero
run_as_context:
- description: Wunero runs as a non-root user
  gid: 568
  group_name: wunero
  uid: 568
  user_name: wunero
screenshots: []
sources:
- https://github.com/XmlmXmlmX/wunero
title: Wunero
train: community
version: 1.0.0
